name: Buld CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install --frozen-lockfile && pnpm run generate

      - name: Build
        run: pnpm run build

      - name: Prepare output
        run: |
          mkdir -p dist
          cp -r ./public ./dist
          cp -r ./.next/standalone/* ./dist
          cp -r ./.next/static ./dist/.next

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tsdb
          path: dist/*
